{{ if .Values.createDefaultPullSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "metastore.defaultImagepullName" . }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Files.Get "files/example-imagepullsecret" | b64enc }}
  {{ end }}