apiVersion: v1
kind: Service
metadata:
  name: {{ include "metastore.fullname" . }}-thrift
  labels:
    {{- include "metastore.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: thrift
  selector:
    {{- include "metastore.selectorLabels" . | nindent 4 }}
