{{- with .Values.ranger }}

apiVersion: v1
kind: Service
metadata:
  name: {{ tpl .fullname $ }}
spec:
  type: NodePort
  ports:
    - name: http
      port: {{ .listenPort }}
      protocol: TCP
      targetPort: {{ .listenPort }}
      nodePort: {{ .nodePort }}
  selector:
    app: ranger-admin-server

{{- end }}
