{{- with .Values.ranger }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ tpl .fullname $ }}
  labels:
    app: ranger-admin-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ranger-admin-server
  template:
    metadata:
        labels:
          app: ranger-admin-server
    spec:
      initContainers:
      - name: mysql-init
        image: busybox:1.31
        imagePullPolicy: Always
        env:
          - name: MYSQL_HOST
            value: {{ $.Values.dataStore.service.clusterIp.fullName }}
        command: ['sh', '-c', 'echo -e "Checking for the availability of MySQL Server deployment"; while ! nc -z ${MYSQL_HOST}  3306; do sleep 1; printf "-"; done; echo -e "  >> MySQL DB Server has started";']
      containers:
        - name: ranger-admin-server
          image: {{ .containerImage }}
          imagePullPolicy: {{ .pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .listenPort }}
              protocol: TCP
          volumeMounts:
            - name: ranger-conf
              mountPath: /opt/mapr/ranger/ranger-2.3.0/ranger-admin/install.properties
              subPath: install.properties
{{- if .ssl.use_custom_truststore }}
            - name: admin-truststore
              mountPath: {{ include "ranger-chart.truststore_dir" . }}/admin_truststore.jks
              subPath: admin_truststore.jks
{{- end }}
      volumes:
        - name: ranger-conf
          secret:
            secretName: ranger-property-file
{{- if .ssl.use_custom_truststore }}
        - name: admin-truststore
          secret:
            secretName: {{ .ssl.truststore_secret_name }}
{{- end }}
      imagePullSecrets:
      - name: imagepull
{{- end }}
