env: "localdev"

## Global; used for defining Names
appName: "{{ .Chart.Name }}"
relName: "{{ .Release.Name }}"
uidName: "{{ .Release.Namespace }}"

kind:
  deployment: dep
  services: svc

dataStore:
  fullname: "{{ .Release.Namespace }}-{{ .Values.kind.deployment }}-mysql"
  containerImage: mysql:5.7
  pullPolicy: Always
  # root database user
  rootPasswd: admin
  # Ranger specific database and user info
  user: admin
  passwd: admin
  dbname: ranger
  listenPort: 3306
  label: mysql

  # Your persistent provider can be either NFS or DF
  # a) to enable NFS mode, please set isNfs=true and provide NFS serverIp
  # b) to enable DF mode, please provide a correct storageClassName. It can be found by issuing:
  # kubectl get sc | grep com.mapr.csi-kdf | tr -s ' ' | cut -f 1 -d ' ' | tail +1
  # Default configuration would be DF, assuming your DF cluster name is cluster.qa.lab
  # NOTE: with NFS case your data won't be cleaned up after uninstalling. WIth DF case it will be
  storage:
    isNfs: true
    serverIp: 16.0.13.105
    pvFullname: "{{ .Release.Namespace }}-{{ .Values.kind.persistentVolumes }}-mysql"
    pvcFullname: "{{ .Release.Namespace }}-{{ .Values.kind.persistentVolumeClaim }}-mysql"
    storageClassName: "cluster-qa-lab"
    storagePath: /nfs/{{ .Release.Namespace }}/mysql-pv/
    accessMode: ReadWriteMany
    size: 5Gi
    mntPath: /var/lib/mysql

  service:
    clusterIp:
      fullName: mysql

    nodePort:
      fullName: mysqlnp
      nodeport: 32114

ranger:
  fullname: "{{ .Release.Namespace }}-ranger"
  containerImage: gcr.io/mapr-252711/ranger-admin-2.3.0:202212130652R
  pullPolicy: Always
  listenPort: 6080
  nodePort: 30004
  # PLEASE NOTE :: Password should be minimum 8 characters with min one alphabet and one numeric.
  # TODO: Use secret https://jira-pro.its.hpecorp.net:8443/browse/EZAF-234
  console_password: &ranger_internal_passwords Admin@123
  user_authentication:
    # UNIX | LDAP
    auth_method: UNIX
    # If you use auth method as LDAP, provide below properties
    # Related documentation is https://docs-datafabric.mip.storage.hpecorp.net/71/Ranger/Configure_LDAP_AD_for_Ranger.html
    ldap_url: ldap://node2:389
    ldap_bind_dn: cn=admin,dc=cluster,dc=com
    ldap_bind_password: mapr
    ldap_groupSearchBase: dc=cluster,dc=com
    ldap_userDNpattern: cn={0},ou=People,dc=cluster,dc=com
    ldap_base_dn: dc=cluster,dc=com

usersync:
  deploymentEnabled: true
  fullname: "{{ .Release.Namespace }}-usersync"
  containerImage: gcr.io/mapr-252711/ranger-usersync-2.3.0:202212130652R
  pullPolicy: Always
  listenPort: 5151
  nodePort: 30005
  usersync_password: *ranger_internal_passwords
  rangerAdminURL: "http://ranger-ranger:6080"
  sync_source:
    # unix | ldap
    sync_method: unix
    # If you use sync method as ldap, provide below properties
    # Related documentation is https://docs-datafabric.mip.storage.hpecorp.net/71/Ranger/Configure_LDAP_AD_for_Ranger.html
    ldap_url: ldap://node2:389
    ldap_bind_dn: cn=admin,dc=cluster,dc=com
    ldap_bind_password: mapr
    ldap_search_base: dc=cluster,dc=com
    sync_group_search_enabled: true
    sync_group_user_map_sync_enabled: true
