apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spark-ts-chart.conifgmapName" . }}
  {{- if .Values.ownerReference.overRide }}
  {{- with  .Values.ownerReference.ownerReferences }}
  ownerReferences: {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- end }}
  labels:
  {{- include "common.labels" (dict "componentName" ( include "spark-ts-chart.conifgmapName" . ) "namespace" .Release.Namespace ) | nindent 4 }}
data:
  post-startup.sh: |
  #!/usr/bin/env bash
  pre-startup.sh: |
    #!/usr/bin/env bash
  spark-defaults.conf: |-
    spark.kubernetes.driver.request.cores {{ .Values.thriftServerResources.driver.requestCores }}
    spark.kubernetes.driver.limit.cores  {{ .Values.thriftServerResources.driver.limitCores }}
    spark.kubernetes.executor.request.cores {{ .Values.thriftServerResources.executor.requestCores }}
    spark.kubernetes.executor.limit.cores {{ .Values.thriftServerResources.executor.limitCores }}

    spark.kubernetes.authenticate.serviceAccountName {{ include "spark-ts-chart.serviceAccountName" . }}
    spark.kubernetes.container.image {{ .Values.image.baseRepository }}/{{ .Values.sparkVersion }}:{{ .Values.image.executorTag }}
    {{- with ( first .Values.imagePullSecrets ) }}
    spark.kubernetes.container.image.pullSecrets {{ .name }}
    {{- end }}
    spark.kubernetes.container.image.pullPolicy {{ .Values.image.pullPolicy }}
    spark.kubernetes.namespace {{ .Release.Namespace }}
    spark.authenticate false
    spark.authenticate.enableSaslEncryption false

    {{- if .Values.tenantIsUnsecure }}
    spark.hadoop.fs.default.name file:///
    {{- else }}
    spark.sql.warehouse.dir maprfs:///apps/{{ .Release.Namespace }}/spark-warehouse
    {{- end }}

    # Fix for SPARK-7819
    spark.sql.hive.metastore.sharedPrefixes  com.mysql.jdbc,org.postgresql,com.microsoft.sqlserver,oracle.jdbc,com.mapr.fs.shim.LibraryLoader,com.mapr.security.JNISecurity,com.mapr.fs.jni,com.mapr.fs.ShimLoader
