apiVersion: v1
kind: Service
metadata:
  name: {{ include "spark-ts-chart.serviceName" . }}
  {{- if .Values.ownerReference.overRide }}
  {{- with  .Values.ownerReference.ownerReferences }}
  ownerReferences: {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- end }}
  labels:
    {{- include "common.labels" (dict "componentName" ( include "spark-ts-chart.serviceName" . ) "namespace" .Release.Namespace ) | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ include "spark-ts-chart.getHttpPortSparkTsUI" . }}
      targetPort: {{ include "spark-ts-chart.getHttpPortSparkTsUI" . }}
      protocol: TCP
      name: http-thrift
    - port: {{ .Values.ports.sparkTsPort }}
      targetPort: {{ .Values.ports.sparkTsPort }}
      protocol: TCP
      name: spark-thrift
  selector:
    {{- include "common.selectorLabels" (dict "componentName" ( include "spark-ts-chart.deploymentName" . )  ) | nindent 4 }}
