apiVersion: v1
kind: Secret
metadata:
  name: spark-ts-secret-configs
  {{- if .Values.ownerReference.overRide }}
  {{- with  .Values.ownerReference.ownerReferences }}
  ownerReferences: {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- end }}
data:
  spark-defaults.conf: {{ include "spark-ts-chart.extraConfigs" . | b64enc }}
