{{- with .Values.usersync }}
{{- if .deploymentEnabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ tpl .fullname $ }}
  labels:
    app: ranger-usersync-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ranger-usersync-service
  template:
    metadata:
      labels:
        app: ranger-usersync-service
    spec:
      containers:
        - name: ranger-usersync-service
          image: {{ .containerImage }}
          imagePullPolicy: {{ .pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .listenPort }}
              protocol: TCP
          volumeMounts:
            - name: usersync-conf
              mountPath: /opt/mapr/ranger/ranger-2.3.0/ranger-usersync/install.properties
              subPath: install.properties
{{- if .ssl.use_custom_truststore }}
            - name: ugsync-truststore
              mountPath: {{ include "ranger-chart.truststore_dir" . }}/ugsync_truststore.jks
              subPath: ugsync_truststore.jks
{{- end }}
      volumes:
        - name: usersync-conf
          secret:
            secretName: usersync-property-file
{{- if .ssl.use_custom_truststore }}
        - name: ugsync-truststore
          secret:
            secretName: {{ .ssl.truststore_secret_name }}
{{- end }}
      imagePullSecrets:
        - name: imagepull
{{- end }}
{{- end }}
