{{ $componentName := include "hivemeta-chart.serviceAccountName" . }}
  {{ if ( and ( .Values.serviceAccount.create) ( not ( lookup "v1" "ServiceAccount" .Release.Namespace $componentName )) ) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $componentName }}
  labels: {{ include "hivemeta-chart.labels" (dict "componentName" $componentName "context" $) | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
