{{ $componentName := printf "%s-svc" .Chart.Name }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $componentName }}
  namespace: {{ .Values.tenantNameSpace }}
  labels:
  {{ include "hivemeta-chart.labels" (dict "componentName" $componentName "context" $) | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: thrift
  selector:
    {{- include "hivemeta-chart.selectorLabels" . | nindent 4 }}