{{- if ( and (.Values.autotix.enable)  (.Values.serviceAccounts.autotix.create)) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "autoticket-generator.hpePrefix" . }}
  {{- if .Values.ownerReference.overRide }}
  {{- with  .Values.ownerReference.ownerReferences }}
  ownerReferences: {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- end }}
{{- end }}
