{{ if .Values.autotix.enable }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "autoticket-generator.certManagerIssuer" . }}
  labels:
  {{- include "autoticket-generator.selectorLabels" . | nindent 4 }}
  {{- if .Values.ownerReference.overRide }}
  {{- with .Values.ownerReference.ownerReferences }}
  ownerReferences: {{- toYaml . | nindent 2 }}
    {{- end }}
    {{- end }}
spec:
  selfSigned: {}
{{ end }}
