{{ if .Values.autotix.enable }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "autoticket-generator.configMapName" . }}
  labels:
  {{- include "autoticket-generator.selectorLabels" . | nindent 4 }}
  {{- if .Values.ownerReference.overRide }}
  {{- with  .Values.ownerReference.ownerReferences }}
  ownerReferences: {{- toYaml . | nindent 2 }}
    {{- end }}
    {{- end }}
data:
  configuration.yaml: |
    {{- toYaml .Values.autotix.configuration | nindent 4 }}
  {{ end }}
