{{ if .Values.autotix.enable }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "autoticket-generator.svcName" . }}
  labels:
    {{- include "autoticket-generator.selectorLabels" . | nindent 4 }}
  {{- if .Values.ownerReference.overRide }}
  {{- with  .Values.ownerReference.ownerReferences }}
  ownerReferences: {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- end }}
spec:
  ports:
    - port: {{ .Values.autotix.port }}
      targetPort: {{ .Values.autotix.targetPort }}
  selector:
    {{- include "autoticket-generator.selectorLabels" . | nindent 4 }}
  {{ end }}