{{ if .Values.autotix.enable }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "autoticket-generator.certManagerCertificate" . }}
  labels:
  {{- include "autoticket-generator.selectorLabels" . | nindent 4 }}
  {{- if .Values.ownerReference.overRide }}
  {{- with  .Values.ownerReference.ownerReferences }}
  ownerReferences: {{- toYaml . | nindent 2 }}
    {{- end }}
    {{- end }}
spec:
  dnsNames:
    - {{ include "autoticket-generator.svcName" . }}.{{ .Release.Namespace }}.svc
    - {{ include "autoticket-generator.svcName" . }}.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: {{ include "autoticket-generator.certManagerIssuer" . }}
  secretName: autoticket-generator-cert
{{ end }}
