{{ if .Values.autotix.enable }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "autoticket-generator.configMapName" . }}
  labels:
  {{- include "autoticket-generator.selectorLabels" . | nindent 4 }}
  {{- if .Values.ownerReference.overRide }}
  {{- with  .Values.ownerReference.ownerReferences }}
  ownerReferences: {{- toYaml . | nindent 2 }}
    {{- end }}
    {{- end }}
data:
  spark_app_labels.yaml: |
    hpe-ezua/app: spark
    hpe-ezua/type: app-service-user
  {{ end }}
