apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spark-images.configmapName" . }}
  {{- if .Values.ownerReference.overRide }}
  {{- with .Values.ownerReference.ownerReferences }}
  ownerReferences: {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- end }}
  labels:
    {{- include "spark-images.labels" . | nindent 4 }}
data:
  DEFAULT_IMAGE: gcr.io/mapr-252711/spark-3.5.1:v3.5.1.1.0
  DEFAULT_IMAGE_SHORT: spark-3.5.1:v3.5.1.1.0
  images.yaml: |
    images:
    - image: gcr.io/mapr-252711/spark-3.5.1:v3.5.1.1.0
      imageShort: spark-3.5.1:v3.5.1.1.0
      sparkVersion: 3.5.1
      labels:
      - lang/java
      - lang/python
      - lang/r
      - lang/scala
      - vendor/ezmeral
      - version/default
      - version/latest
      - controller/spark-operator
      - controller/livy


    - image: gcr.io/mapr-252711/spark-3.5.0:v3.5.0.5.0
      imageShort: spark-3.5.0:v3.5.0.5.0
      sparkVersion: 3.5.0
      labels:
      - feature/gpu
      - lang/java
      - lang/python
      - lang/r
      - lang/scala
      - vendor/ezmeral
      - version/legacy
      - controller/spark-operator
      - controller/livy


    - image: gcr.io/mapr-252711/apache-spark:3.5.1-en2
      imageShort: apache-spark:3.5.1-en2
      description: Open source Spark image for Java/Scala applications
      sparkVersion: 3.5.1
      labels:
      - lang/java
      - lang/py
      - lang/r
      - lang/scala
      - vendor/apache
      - version/latest
      - controller/spark-operator


    - image: gcr.io/mapr-252711/apache-spark:3.5.0-en2
      imageShort: apache-spark:3.5.0-en2
      description: Open source Spark image for Java/Scala applications
      sparkVersion: 3.5.0
      labels:
      - feature/gpu
      - lang/java
      - lang/py
      - lang/r
      - lang/scala
      - vendor/apache
      - version/legacy
      - controller/spark-operator
