{{ if .Values.createDefaultPullSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.defaultPullSecret }}
  {{- if .Values.ownerReference.overRide }}
  {{- with  .Values.ownerReference.ownerReferences }}
  ownerReferences: {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- end }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Files.Get "files/example-imagepullsecret" | b64enc }}
{{ end }}
