image:
  repository: gcr.io/mapr-252711/apache-livy-0.8.0-pre
  pullPolicy: Always
  tag: "202103261742"

imagePullSecrets:
   - name: imagepull

createDefaultPullSecret: true

nameOverride: ""
fullnameOverride: ""

serviceAccounts:
  livy:
    create: true
    annotations: {}
    name: ""
  spark:
    # ServiceAccount for Spark Applications
    create: true
    annotations: {}
    name: ""

rbac:
  create: true

podAnnotations: {}

service:
  type: NodePort
  port: 8998

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

env:
  - name: SPARK_CONF_spark_kubernetes_container_image
    value: gcr.io/mapr-252711/apache-spark-livy-3.1.1:202103261742
    # Other available images:
    # gcr.io/mapr-252711/apache-spark-py-livy-3.1.1:202103261742
    # gcr.io/mapr-252711/apache-spark-r-livy-3.1.1:202103261742
  - name: SPARK_CONF_spark_kubernetes_container_image_pullPolicy
    value: Always
  # - name: SPARK_CONF_spark_kubernetes_container_image_pullSecrets
  #   value: imagepull
