image:
  repository: gcr.io/mapr-252711/apache-livy-0.8.0-pre
  pullPolicy: Always
  tag: "202107201935"

imagePullSecrets:
   - name: imagepull

createDefaultPullSecret: true

nameOverride: ""
fullnameOverride: ""

serviceAccounts:
  livy:
    create: true
    annotations: {}
    name: ""
  spark:
    # ServiceAccount for Spark Applications
    create: true
    annotations: {}
    name: ""

rbac:
  create: true

podAnnotations: {}

service:
  type: NodePort
  port: 8998

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 1000m
    memory: 1Gi

nodeSelector: {}

tolerations: []

affinity: {}

# Configuration of Livy Session Recovery
sessionrecovery:
  kind: disabled
# sessionrecovery:
#   kind: pvc
#   pvcname: <pvcname>

security:
  https: true

env:
  - name: SPARK_CONF_spark_kubernetes_container_image
    value: gcr.io/mapr-252711/apache-spark-livy-3.1.1:202107201935
    # Other available images:
    # gcr.io/mapr-252711/apache-spark-py-livy-3.1.1:202107201935
    # gcr.io/mapr-252711/apache-spark-r-livy-3.1.1:202107201935
  - name: SPARK_CONF_spark_kubernetes_container_image_pullPolicy
    value: Always
  - name: SPARK_CONF_spark_kubernetes_container_image_pullSecrets
    value: imagepull
  - name: SPARK_CONF_spark_kubernetes_driver_request_cores
    value: "1"
  - name: SPARK_CONF_spark_kubernetes_driver_limit_cores
    value: "1"
  - name: SPARK_CONF_spark_kubernetes_executor_request_cores
    value: "1"
  - name: SPARK_CONF_spark_kubernetes_executor_limit_cores
    value: "1"
