{{ if .Values.createDefaultPullSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.defaultPullSecret }}
  namespace: {{ include "tenant-operator.namespace" . }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Files.Get "files/example-imagepullsecret" | b64enc }}
  {{ end }}
