apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "tenant-validator.postInstallHookName" . }}
  namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
      serviceAccountName: {{ include "tenant-validator.hpePrefix" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: post-install-container
          image: "{{ .Values.image.baseRepository }}/{{ .Values.image.validatorImageName }}:{{ .Values.image.validatorTag }}"
          imagePullPolicy: IfNotPresent
          command: ["/opt/validator/deploy/tenantvalidator-gencert.sh", "{{ .Release.Namespace }}"]
      restartPolicy: OnFailure
