apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "tenant-validator.preDeleteHookName" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-delete, pre-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
spec:
  template:
    spec:
      serviceAccountName: {{ include "tenant-validator.hpePrefix" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: pre-delete-container
          image: "{{ .Values.image.baseRepository }}/{{ .Values.image.validatorImageName }}:{{ .Values.image.validatorTag }}"
          imagePullPolicy: IfNotPresent
          command: ["/opt/validator/deploy/tenantvalidator-uninstall.sh", "{{ .Release.Namespace }}"]
      restartPolicy: OnFailure
