apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tenant-validator.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
  {{- include "tenant-validator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
    {{- include "tenant-validator.selectorLabels" . | nindent 8 }}
    {{- with .Values.customLabels }}
    {{- toYaml . | nindent 8 }}
    {{- end }}
    spec:
      serviceAccountName: {{ include "tenant-validator.hpePrefix" . }}
      automountServiceAccountToken: {{ .Values.automountSAToken }}
      priorityClassName: {{ .Values.priorityClassName }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
      {{- include "tenant-operator.podAntiAffinity.preferred" . | nindent 12 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ include "tenant-validator.name" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        image: "{{ .Values.image.baseRepository }}/{{ .Values.image.validatorImageName }}:{{ .Values.image.validatorTag }}"
        resources:
        {{- toYaml .Values.resources | nindent 12 }}
        env:
        {{- include "tenant-validator.env" . | nindent 12 }}
        volumeMounts:
        {{- include "tenant-validator.volumesMounts" . | nindent 12 }}
      volumes:
      {{- include "tenant-validator.volumes" . | nindent 8 }}
