{{ if .Values.createImagetPullSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullSecretsName }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Files.Get "files/example-imagepullsecret" | b64enc }}
  {{ end }}
