---
{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "livy-chart.roleName" . }}
  {{- if .Values.ownerReference.overRide }}
  {{- with .Values.ownerReference.ownerReferences }}
  ownerReferences: {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- end }}
  labels:
  {{- include "livy-chart.labels" . | nindent 4 }}
rules:
- apiGroups:
    - ""
  resources:
    - configmaps
    - pods
    - services
    - secrets
  verbs:
    - "*"
- apiGroups:
    - ""
  resources:
    - namespaces
  verbs:
    - get
    - list
{{- end }}

---
{{- if and .Values.rbac.create .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "livy-chart.roleBindingName" . }}
  {{- if .Values.ownerReference.overRide }}
  {{- with .Values.ownerReference.ownerReferences }}
  ownerReferences: {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- end }}
  labels:
  {{- include "livy-chart.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "livy-chart.roleName" . }}
subjects:
- name: {{ include "livy-chart.serviceAccountName" . }}
  kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
{{- end }}
