apiVersion: v1
kind: Service
metadata:
  name: {{ include "livy-chart.serviceName" . }}
  {{- if .Values.ownerReference.overRide }}
  {{- with .Values.ownerReference.ownerReferences }}
  ownerReferences: {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- end }}
  labels:
    {{- include "livy-chart.labels" . | nindent 4 }}
spec:
  type: NodePort
  sessionAffinity: ClientIP
  ports:
    - port: {{ .Values.ports.livyHttpPort }}
      targetPort: {{ .Values.ports.livyHttpPort }}
      protocol: TCP
      {{- if or (not .Values.tenantIsUnsecure) (.Values.livySsl.useCustomKeystore) }}
      name: https-livy
      {{ else }}
      name: http-livy
      {{- end }}
  selector:
    {{- include "livy-chart.selectorLabels" . | nindent 4 }}
