apiVersion: v1
kind: Service
metadata:
  name: {{ include "livy-chart.serviceName" . }}
  {{- if .Values.ownerReference.overRide }}
  {{- with .Values.ownerReference.ownerReferences }}
  ownerReferences: {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- end }}
  labels:
    {{- include "common.labels" (dict "componentName" ( include "livy-chart.serviceName" . ) "namespace" .Release.Namespace ) | nindent 4 }}
spec:
  type: NodePort
  sessionAffinity: ClientIP
  ports:
    - port: {{ .Values.ports.livyHttpPort }}
      targetPort: {{ .Values.ports.livyHttpPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "common.selectorLabels" (dict "componentName" ( include "livy-chart.name" . ) ) | nindent 4 }}
