{{ if ( .Values.serviceAccount.create ) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "livy-chart.serviceAccountName" . }}
  labels:
  {{- include "livy-chart.labels" . | nindent 4 }}
  {{- if .Values.ownerReference.overRide }}
  {{- with .Values.ownerReference.ownerReferences }}
  ownerReferences: {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- end }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
