{{ if .Values.istio.virtualService.create }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-vs
spec:
  hosts:
    - {{ .Values.istio.virtualService.endpoint | required "\nValid .Values.istio.virtualService.endpoint is required !" }}
  gateways:
    - {{ .Values.istio.virtualService.istioGateway }}
  http:
    - match:
        - uri:
            prefix: {{ .Values.istio.virtualService.prefix }}
      route:
        - destination:
            host: {{ include "livy-chart.serviceName" . }}.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: {{ .Values.ports.livyHttpPort }}
  {{ end }}
