apiVersion: v1
kind: Service
metadata:
  name: {{ include "spark-hs-chart.fullname" . }}
  {{- if .Values.ownerReference.overRide }}
  {{- with  .Values.ownerReference.ownerReferences }}
  ownerReferences: {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ include "spark-hs-chart.name" . }}
    helm.sh/chart: {{ include "spark-hs-chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: https-sparkhs
      port: {{ .Values.ports.httpsPort }}
      targetPort: {{ .Values.ports.httpsPort }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "spark-hs-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
