# Default values for spark-hs chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# replicaCount -- Desired number of pods, leaderElection will be enabled
# if this is greater than 1
replicaCount: 1

image:
  # -- Image repository
  repository: gcr.io/mapr-252711/spark-hs-2.4.7
  # -- Image pull policy
  pullPolicy: Always
  # -- Overrides the image tag whose default is the chart appVersion.
  tag: "202106220630P141"

# -- Image pull secrets
imagePullSecrets:
  - name: imagepull

createDefaultPullSecret: false
defaultPullSecret: imagepull

# -- String to partially override `spark-operator.fullname` template (will maintain the release name)
nameOverride: ""

# -- String to override release name
fullnameOverride: ""

# -- restart policy
restartPolicy: "Always"

automountServiceAccountToken: true

progressDeadlineSeconds: 600

revisionHistoryLimit: 10

#sparkVersion for the applications
sparkVersion: spark-2.4.7

#HPE tenant namespace info
tenantIsUnsecure: false

#HPE tenant namespace service account
serviceAccount:
  # Specifies whether a service account should be created
  # This will look for existing hpe-{{ ReleaseNamespace }} ServiceAccount and use it if it exists and creates when it is not present
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use. Please only use the tenant Service Account
  # This name is used only when create ServiceAccount option is set to false.
  # Otherwise a new Service Account is created using hpe-{{ ReleaseNamespace }}
  name: ""

#Create RBAC for the Service Account
rbac:
  #RBAC is created only when this flag is true and ServiceAccount.create is also true
  create: true

podSecurityContext: {}

#service info
service:
  type: NodePort

#container ports
ports:
  sshPort: 22
  sshHostPort: 7779
  httpPort: 18080
  httpsPort: 18480

# resources -- Pod resource requests and limits
resources:
   limits:
     cpu: 8000m
     memory: 8Gi
     ephemeral-storage: 30Gi
   requests:
     cpu: 2000m
     memory: 8Gi
     ephemeral-storage: 30Gi

#owner Reference
ownerReference:
  overRide: false
  ownerReferences: {}

#configurations for event log storage
eventlogstorage:
  kind: maprfs #supported types are pvc and maprfs
  pvcname: "" #example pvc; to be replaced by an existing pvc in the tenant namespace
