apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spark-hs-chart.fullname" . }}
  {{- if .Values.ownerReference.overRide }}
  {{- with  .Values.ownerReference.ownerReferences }}
  ownerReferences: {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ include "spark-hs-chart.name" . }}
    helm.sh/chart: {{ include "spark-hs-chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  enablePVC: {{ .Values.pvc.enablePVC | quote }}
  {{- range $key, $val := .Values.environment }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- if .Values.pvc.enablePVC }}
  {{- range $key, $val := omit .Values.pvc "enablePVC" }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- else }}
  {{- range $key, $val := .Values.hdfs }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- end }}
