{{- if and .Values.pvc.enablePVC (not .Values.pvc.existingClaimName) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "spark-hs-chart.pvcName" . }}
  labels:
    app.kubernetes.io/name: {{ include "spark-hs-chart.name" . }}
    helm.sh/chart: {{ include "spark-hs-chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.pvc.storageSize | quote }}
  {{- if .Values.pvc.storageClass }}
  {{- if (eq "-" .Values.pvc.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.pvc.storageClass }}"
  {{- end }}
  {{- end }}
{{- end }}
