apiVersion: v1
kind: Service
metadata:
  name: {{ include "spark-hs-chart.fullname" . }}
  {{- if .Values.ownerReference.overRide }}
  {{- with  .Values.ownerReference.ownerReferences }}
  ownerReferences: {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ include "spark-hs-chart.name" . }}
    helm.sh/chart: {{ include "spark-hs-chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- if .Values.service.annotations }}
  annotations:
  {{ toYaml .Values.service.annotations | trim | indent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port.number }}
    targetPort: historyport
    protocol: TCP
    name: {{ .Values.service.port.name }}
    {{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePort))) }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "spark-hs-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
