{{ if .Values.istio.authPolicy.create }}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ .Release.Name }}-auth-policy
spec:
  action: CUSTOM
  provider:
    name: oauth2-proxy
  rules:
    - to:
        - operation:
            hosts:
              - {{ .Values.istio.virtualService.endpoint }}
  selector:
    matchLabels:
      {{- include "common.selectorLabels" (dict "componentName" .Chart.Name ) | nindent 6 }}
{{ end }}
