{{- if .Values.eventlogstorage.volumePluginSpec -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "spark-hs-chart.pvName" .  }}
  labels:
    app.kubernetes.io/name: {{ include "spark-hs-chart.name" . }}
    helm.sh/chart: {{ include "spark-hs-chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  capacity:
    storage: {{ .Values.eventlogstorage.storageSize }}
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: {{ .Release.Namespace }}
    name: {{ include "spark-hs-chart.pvcName" . }}
  {{- toYaml .Values.eventlogstorage.volumePluginSpec | nindent 2 }}
{{- end }}
