{{- if eq .Values.eventlogstorage.kind "s3"  }}
apiVersion: v1
kind: Secret
metadata:
  name: spark-hs-s3-secret
data:
  s3_access_key_file: |
    {{ .Values.eventlogstorage.s3AccessKey | b64enc }}
  s3_secret_key_file: |
    {{ .Values.eventlogstorage.s3SecretKey | b64enc }}
{{- end }}
