{{ $componentName := include "spark-hs-chart.serviceAccountName" . }}
{{ if ( and ( .Values.serviceAccount.create)  ( not ( lookup "v1" "ServiceAccount" .Release.Namespace $componentName )) )  }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $componentName }}
  labels:
  {{- include "common.labels" (dict "componentName" $componentName "namespace" .Release.Namespace ) | nindent 4 }}
  {{- if .Values.ownerReference.overRide }}
  {{- with  .Values.ownerReference.ownerReferences }}
  ownerReferences: {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- end }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
