{{ $componentName := printf "%s-svc" .Chart.Name }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $componentName }}
  {{- if .Values.ownerReference.overRide }}
  {{- with  .Values.ownerReference.ownerReferences }}
  ownerReferences: {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- end }}
  labels:
    {{- include "common.labels" (dict "componentName" $componentName "namespace" .Release.Namespace ) | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.ports.httpPort }}
      targetPort: {{ .Values.ports.httpPort }}
      protocol: TCP
    - name: https
      port: {{ .Values.ports.httpsPort }}
      targetPort: {{ .Values.ports.httpsPort }}
      protocol: TCP
  selector:
    {{- include "common.selectorLabels" (dict "componentName" .Chart.Name ) | nindent 4 }}
