# Default values for spark-ts-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# replicaCount -- Desired number of pods, leaderElection will be enabled
# if this is greater than 1
replicaCount: 1

image:
  # -- Image repository
  baseRepository: gcr.io/mapr-252711
  # -- Image Name
  imageName: spark-ts-2.4.7
  # -- Overrides the image tag whose default is the chart appVersion.
  tag: "202106291513C"
  # -- Image pull policy
  pullPolicy: Always

# -- Image pull secrets
imagePullSecrets:
  - name: imagepull

# -- String to partially override `spark-operator.fullname` template (will maintain the release name)
nameOverride: ""

# -- String to override release name
fullnameOverride: ""

# -- restart policy
restartPolicy: "Always"

automountServiceAccountToken: true

progressDeadlineSeconds: 600

revisionHistoryLimit: 10

#sparkVersion for the applications
sparkVersion: spark-2.4.7

#HPE tenant namespace info
tenantIsUnsecure: false

createDefaultPullSecret: false
defaultPullSecret: imagepull

#HPE tenant namespace service account
serviceAccount:
  # Specifies whether a service account should be created
  # This will look for existing hpe-{{ ReleaseNamespace }} ServiceAccount and use it if it exists and creates when it is not present
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use. Please only use the tenant Service Account
  # This name is used only when create ServiceAccount option is set to false.
  # Otherwise a new Service Account is created using hpe-{{ ReleaseNamespace }}
  name: ""

#RBAC for the ServiceAccount
rbac:
  #RBAC is created only when this flag is true and ServiceAccount.create is also true
  create: true

#Resources for thrift Server driver and executor pods
thriftServerResources:
  driver:
    requestCores: 2
    limitCores: 2
  executor:
    requestCores: 2
    limitCores: 2

podSecurityContext: {}

#service info
service:
  type: NodePort

#container ports
ports:
  sshPort: 22
  sshHostPort: 7780
  httpPort: 4040
  httpsPort: 4440
  sparkTsPort: 2304

# resources -- Pod resource requests and limits
resources:
  limits:
    cpu: 8000m
    memory: 8Gi
    ephemeral-storage: 30Gi
  requests:
    cpu: 2000m
    memory: 8Gi
    ephemeral-storage: 30Gi

#owner Reference
ownerReference:
  overRide: false
  ownerReferences: {}

#hive site source
hiveSiteSource: hivesite-cm
