{{ $componentName := include "spark-hs-chart.serviceAccountName" . }}
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $componentName }}
  labels: {{ include "spark-hs-chart.labels" (dict "componentName" $componentName "context" $) | nindent 4 }}
  namespace: {{ .Values.tenantNameSpace }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
