{{ $componentName := .Chart.Name }}
{{ $configmapName := printf "%s-cm" .Chart.Name  }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spark-client-chart.fullname" . }}
  {{- if .Values.ownerReference.overRide }}
  {{- with  .Values.ownerReference.ownerReferences }}
  ownerReferences: {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- end }}
  labels:
    {{- include "spark-client-chart.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "spark-client-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "spark-client-chart.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        {{- include "spark-client-chart.imagepullSecrets" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        {{- include "common.volumes" (dict "configmapName" $configmapName "componentName" $componentName) | nindent 8 }}
        {{- include "sssd.volumes" . | nindent 8 }}
        {{ if .Values.datafabric.fullIntegrationEnabled }}
        {{ include "common.security.volumes" . | nindent 8 }}
        {{ include "sssd.security.volumes" . | nindent 8 }}
        {{ end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}/{{ .Values.image.imageName }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- include "common.defaultEnv" (dict "containerName" .Chart.Name) | nindent 12 }}
            - name: SSH_PORT
              value: {{ .Values.service.port.targetPort | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- include "spark-client.volumeMounts" . | nindent 12 }}

      serviceAccountName: {{ include "spark-client-chart.serviceAccountName" . }}
      automountServiceAccountToken: true
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
