{{- if .Values.serviceAccount.createRbac }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "spark-client-chart.fullname" . }}
  {{- if .Values.ownerReference.overRide }}
  {{- with  .Values.ownerReference.ownerReferences }}
  ownerReferences: {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- end }}
  labels:
    {{- include "spark-client-chart.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  - extensions
  - apps
  resources:
  - pods
  - configmaps
  - services
  - enpoints
  - secrets
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - resourcequotas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sparkoperator.k8s.io
  resources:
  - sparkapplications
  - sparkapplications/status
  - scheduledsparkapplications
  - scheduledsparkapplications/status
  verbs:
  - "*"

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "spark-client-chart.fullname" . }}
  labels:
    {{- include "spark-client-chart.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "spark-client-chart.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "spark-client-chart.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
