apiVersion: v1
kind: Service
metadata:
  name: {{ include "spark-client-chart.fullname" . }}
  {{- if .Values.ownerReference.overRide }}
  {{- with  .Values.ownerReference.ownerReferences }}
  ownerReferences: {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- end }}
  labels:
    {{- include "spark-client-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port.number }}
      targetPort: {{ .Values.service.port.targetPort }}
      protocol: {{ .Values.service.port.protocol }}
      name: "ssh"
  selector:
    {{- include "spark-client-chart.selectorLabels" . | nindent 4 }}
