apiVersion: v2
name: sparkhs
description: A Helm chart for Spark History Server
type: application
version: 0.4.11
appVersion: "3.5.0.3"
dependencies:
  - name: common
    repository: "file://../../common/"
    version: 0.1.0
