{{ $componentName := printf "%s-svc" .Chart.Name }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $componentName }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.ownerReference.overRide }}
  {{- with  .Values.ownerReference.ownerReferences }}
  ownerReferences: {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- end }}
  labels:
    {{- include "common.labels" (dict "componentName" $componentName "namespace" .Release.Namespace ) | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: thrift
  selector:
    {{- include "common.selectorLabels" (dict "componentName" .Chart.Name ) | nindent 4 }}
