{{ $componentName := printf "%s-ext-svc" .Chart.Name }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $componentName }}
  {{- if .Values.ownerReference.overRide }}
  {{- with  .Values.ownerReference.ownerReferences }}
  ownerReferences: {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- end }}
  labels:
    {{- include "common.labels" (dict "componentName" $componentName "namespace" .Release.Namespace ) | nindent 4 }}
spec:
  type: {{ .Values.externalService.type }}
  ports:
    - name: {{ $componentName }}
      port: {{.Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.port }}
  selector:
  {{- include "common.selectorLabels" (dict "componentName" .Chart.Name ) | nindent 4 }}
