{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "autoticket-generator.hpePrefix" . }}
  namespace: {{ include "autoticket-generator.namespace" . }}
{{- end }}
