---
{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "livy-chart.roleName" . }}
  {{- if .Values.ownerReference.overRide }}
  {{- with  .Values.ownerReference.ownerReferences }}
  ownerReferences: {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- end }}
  labels:
  {{- include "common.labels" (dict "componentName" ( include "livy-chart.roleName" . ) "namespace" .Release.Namespace ) | nindent 4 }}
rules:
- apiGroups:
    - ""
  resources:
    - configmaps
    - pods
    - services
  verbs:
    - "*"
{{- end }}

---
{{- if and .Values.rbac.create .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "livy-chart.roleBindingName" . }}
  {{- if .Values.ownerReference.overRide }}
  {{- with  .Values.ownerReference.ownerReferences }}
  ownerReferences: {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- end }}
  labels:
  {{- include "common.labels" (dict "componentName" ( include "livy-chart.roleBindingName" . ) "namespace" .Release.Namespace ) | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "livy-chart.roleName" . }}
subjects:
- name:  {{ include "livy-chart.serviceAccountName" . }}
  kind: ServiceAccount
{{- end }}
