apiVersion: v1
kind: Service
metadata:
  name: {{ include "livy-chart.httpServiceName" . }}
  {{- if .Values.ownerReference.overRide }}
  {{- with  .Values.ownerReference.ownerReferences }}
  ownerReferences: {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- end }}
  labels:
    {{- include "common.labels" (dict "componentName" ( include "livy-chart.httpServiceName" . ) "namespace" .Release.Namespace ) | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.ports.livyHttpPort }}
      targetPort: {{ .Values.ports.livyHttpPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "common.selectorLabels" (dict "componentName" ( include "livy-chart.name" . ) ) | nindent 4 }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "livy-chart.internalServiceName" . }}
  {{- if .Values.ownerReference.overRide }}
  {{- with  .Values.ownerReference.ownerReferences }}
  ownerReferences: {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- end }}
  labels:
  {{- include "common.labels" (dict "componentName" ( include "livy-chart.internalServiceName" . ) "namespace" .Release.Namespace ) | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    {{- range $i, $e := untilStep ( int .Values.ports.livyInternalPortStart ) ( add1 .Values.ports.livyInternalPortEnd | int ) 1 }}
    - port: {{ $e }}
      name: internal-{{ $e }}
      protocol: TCP
    {{- end }}
  selector:
    {{- include "common.selectorLabels" (dict "componentName" ( include "livy-chart.name" . ) ) | nindent 4 }}
