apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "spark-operator.clusterrolebinding" . }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
    namespace: {{ include "spark-operator.sparknamespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "spark-operator.clusterrole" . }}
  apiGroup: rbac.authorization.k8s.io
