kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.webhook.name }}
  namespace: {{ include "spark-operator.sparknamespace" . }}
spec:
  ports:
  - port: {{ .Values.webhook.port }}
    targetPort: {{ .Values.webhook.targetPort }}
    name: webhook
  selector:
  {{- include "spark-operator.labels" . | nindent 4 }}
