apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "spark-operator.fullname" . }}-webhook-init
  namespace: {{ include "spark-operator.sparknamespace" . }}
  labels:
  {{- include "spark-operator.labels" . | nindent 4 }}
spec:
  backoffLimit: 3
  template:
    metadata:
      name: {{ include "spark-operator.fullname" . }}-webhook-init
      labels:
        {{- include "spark-operator.labels" . | nindent 8 }}
    spec:
      imagePullSecrets: {{- toYaml .Values.imagePullSecrets | nindent 6 }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      restartPolicy: Never
      containers:
      - name: main
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/usr/bin/gencerts.sh", "-n", "{{ include "spark-operator.sparknamespace" . }}", "-s", "{{ include "spark-operator.fullname" . }}-webhook", "-p"]
