apiVersion: v1
kind: Service
metadata:
  name: {{ include "pxc-database.fullname" . }}
  labels:
    {{ include "pxc-external-service.labels" . }}
spec:
  selector:
    app.kubernetes.io/component: {{ .Values.externalService.component }}
    app.kubernetes.io/instance: {{ include "pxc-database.fullname" . }}
    app.kubernetes.io/name: {{ .Values.externalService.selectName }}
  type: {{ .Values.externalService.type }}
  ports:
    - name: {{ .Values.externalService.name }}
      port: {{ .Values.externalService.port }}
      protocol: TCP
      targetPort: {{ .Values.externalService.port }}