# Default values for hivemeta-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# replicaCount -- Desired number of pods, leaderElection will be enabled
# if this is greater than 1
replicaCount: 1

image:
  # -- Image repository
  repository: gcr.io/mapr-252711
  # -- Image name
  imageName: hivemeta-3.1.3
  # -- Image pull policy
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "202405290722R"

# -- Whether to create a default pull secret
createDefaultPullSecret: false
# -- Default pull secret name to be created, update it in imagePullSecrets's name
defaultPullSecret: imagepull-hivemeta

# -- Image pull secrets, name set to imagepull, change here if chart is creating defaultPullSecret
imagePullSecrets:
  - name: imagepull

# -- String to partially override `spark-operator.fullname` template (will maintain the release name)
nameOverride: ""

# -- String to override release name
fullnameOverride: ""

# -- restart policy
restartPolicy: "Always"

hiveSecret: "hivemeta-secret"
mysqlDB: false

automountServiceAccountToken: true

#HPE tenant namespace info
tenantIsUnsecure: false

#HPE tenant namespace service account
serviceAccount:
  # Specifies whether a service account should be created
  # Default Service account is hpe-{{ ReleaseNamespace }}, which is created by Tenant operator.
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # This name is used only when create ServiceAccount option is set to true.
  name: ""

#RBAC for the ServiceAccount
rbac:
  #RBAC is created only when this flag is true and ServiceAccount.create is also true
  create: false

podSecurityContext: {}

#service info
service:
  type: ClusterIP
  port: 9083
  name: "hivemeta-svc"

externalService:
  type: NodePort
  name: "hivemeta-ext-svc"

#container ports
ports:
  sshPort: 22
  queryPort: 9083

# resources -- Pod resource requests and limits
resources:
  limits:
    cpu: 8000m
    memory: 8Gi
    ephemeral-storage: 46Gi
  requests:
    cpu: 2000m
    memory: 8Gi
    ephemeral-storage: 46Gi

#owner Reference
ownerReference:
  overRide: false
  ownerReferences: {}
