{{ if empty .Values.imagePullSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.defaultPullSecret }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Files.Get "files/example-imagepullsecret" | b64enc }}
{{ end }}
